Repository team-x-fun/shiftend, pull requests merged in 2020-10, with the labels that each got.

#162 shift情報に変なデータがあったときにスルーする
  lib/repositories/shift_repository.dart
  lib/repositories/shift_request_repository.dart
Labels: bug

#165 apkファイルをdeploygateにpushするGithubActionsの追加
  .github/workflows/test_and_build.yml
  README.md
Labels: deployment, infrastructure

#164 make generateの最適化
  build.yaml
  lib/models/announcement/announcement.g.dart
  lib/models/holiday/holiday.g.dart
  lib/models/member/member.g.dart
  lib/models/organization/organization.g.dart
  lib/models/personnel/personnel.g.dart
  lib/models/shift/shift.g.dart
  lib/models/user/user.g.dart
  lib/pages/setting/announcement_list/announcement_list_state.dart
Labels: infrastructure

#163 起動時のエラーを修正
  lib/pages/calendar/calendar_state_controller.dart
Labels: bug

#152 シフト追加画面にメンバーを表示
  lib/pages/addshift/addshift_item.dart
  lib/pages/addshift/addshift_page.dart
  lib/pages/calendar/calendar_state.dart
  lib/pages/calendar/calendar_state.freezed.dart
  lib/pages/calendar/calendar_state_controller.dart
  lib/pages/calendar/widgets/calendar_list_widget.dart
  lib/pages/calendar/widgets/calendar_widget.dart
Labels: enhancement, review fixing
