Repository team-x-fun/shiftend, pull requests merged in 2020-07, with the labels that each got.

#28 データをRepositoryのモックデータに入れ替える＆メンバーリストのレイアウトを整理する
  lib/member.dart
  lib/member_item.dart
  lib/member_page.dart
  lib/repositories/interfaces/user_repository_interface.dart
  lib/repositories/mocks/user_repository_mock.dart
  lib/repositories/user_repository.dart
Labels: flutter

#29 カレンダー画面のとりあえずベースを作った
  lib/main.dart
  lib/pages/calendar/calendar_page.dart
  pubspec.lock
  pubspec.yaml
Labels: flutter

#30 設定画面のレイアウト作成
  lib/main.dart
  lib/pages/setting/setting_account_item.dart
  lib/pages/setting/setting_header_item.dart
  lib/pages/setting/setting_list_item.dart
  lib/pages/setting/setting_page.dart
Labels: flutter

#33 CalendarPageのリファクタ
  lib/main.dart
  lib/pages/calendar/calendar_page.dart
  lib/pages/calendar/calendar_state.dart
  lib/pages/calendar/calendar_state.freezed.dart
  lib/pages/calendar/calendar_state_controller.dart
  lib/pages/calendar/widgets/calendar_list_widget.dart
  lib/pages/calendar/widgets/calendar_widget.dart
  lib/pages/calendar/widgets/marker_widget.dart
  lib/util/formatters.dart
  pubspec.lock
  pubspec.yaml
Labels: review fixing

#32 [設定画面]appbarの追加
  lib/pages/setting/setting_account_item.dart
  lib/pages/setting/setting_list_item.dart
  lib/pages/setting/setting_page.dart
Labels: flutter

#60 Loginの機能
  lib/main.dart
  lib/pages/login/login_page.dart
  lib/pages/login/login_state.dart
  lib/pages/login/login_state.freezed.dart
  lib/pages/login/login_state_controller.dart
  lib/pages/setting/setting_account_item.dart
  lib/pages/setting/setting_logout_item.dart
  lib/pages/setting/setting_page.dart
  lib/repositories/interfaces/user_repository_interface.dart
  lib/repositories/mocks/user_repository_mock.dart
  lib/repositories/user_repository.dart
Labels: enhancement, flutter

#48 メンバーレベルを変更できるようなダイアログの実装
  lib/main.dart
  lib/member_item.dart
  lib/member_page.dart
  lib/pages/member/member_item.dart
  lib/pages/member/member_level_dialog.dart
  lib/pages/member/member_page.dart
  lib/pages/member/member_provider.dart
Labels: enhancement, flutter, review fixing
