Repository team-x-fun/shiftend, pull requests merged in 2020-09, with the labels that each got.

#104 requestShifts[today]がnullのときのハンドリング
  lib/pages/calendar/calendar_state_controller.dart
Labels: bug

#108 自分のシフトに色をつけた
  lib/pages/calendar/widgets/calendar_list_item_widget.dart
Labels: enhancement

#107 組織の基本要員のモデル作成
  lib/models/models.dart
  lib/models/organization/organization.dart
  lib/models/organization/organization.freezed.dart
  lib/models/organization/organization.g.dart
  lib/models/personnel/personnel.dart
  lib/models/personnel/personnel.freezed.dart
  lib/models/personnel/personnel.g.dart
Labels: enhancement

#138 サインアウトしたときに，LoginStateの組織データのリセットを掛ける修正
  lib/models/organization/organization.dart
  lib/models/organization/organization.freezed.dart
  lib/pages/login/login_state.dart
  lib/pages/login/login_state.freezed.dart
  lib/pages/login/login_state_controller.dart
  lib/pages/setting/setting_org/setting_org_state_controller.dart
  lib/pages/user/user_page.dart
  lib/pages/user/widgets/org_select_widget.dart
  lib/repositories/organization_repository.dart
Labels: bug

#147 [ci skip]pre-commitのインストール方法の記載
  README.md
Labels: documentation

#150 定休日の追加削除できるようにした
  lib/pages/setting/setting_org/setting_org_page.dart
  lib/pages/setting/setting_org/setting_org_state.dart
  lib/pages/setting/setting_org/setting_org_state.freezed.dart
  lib/pages/setting/setting_org/setting_org_state_controller.dart
  lib/pages/setting/setting_org/widgets/setting_regular_holiday_dialog.dart
Labels: enhancement, review fixing
